# Basic information about the project and repo
site_name: New Docs
repo_url: https://github.com/MSP2CSPadmin/docs
repo_name: MSP2CSPadmin/docs
edit_uri: edit/main/docs/

# Customising the mkdocs-material theme
theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  font:
    text: Inter
    code: Open Sans
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: red
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - toc.follow
    - search.suggest 
    - search.highlight
    - search.share
    - header.autohide
    - content.code.annotate
    - content.tabs.link
    
  icon:
    repo: fontawesome/brands/git-alt 

# Make changes to the nav when you add new pages or edit existing ones.

nav:
  - Home: index.md
  - About : about.md
  - Extracurricular:
    - Games: extracurricular/games.md
    - Music: extracurricular/music.md
    - Sports: 
      - Volleyball: extracurricular/sports/volleyball.md
      - Football: extracurricular/sports/football.md
    - Coding:
      - Robotics: extracurricular/coding/robotics.md
      - Programming: extracurricular/coding/programming.md
  - Contributing: contributing.md
  - New Page: page.md

    
# Add more features to the look of the page
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MSP2CSPadmin/docs
    - icon: fontawesome/brands/instagram
      link: https://github.com/MSP2CSPadmin/docs
    - icon: fontawesome/brands/linkedin
      link: https://github.com/MSP2CSPadmin/docs
    - icon: fontawesome/brands/twitter 
      link: https://github.com/MSP2CSPadmin/docs
      
  consent:
    title: Cookie consent
    actions:
      - accept
      - manage
      # - reject
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    provider: mike
  
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target=_blank>feedback form</a>.

# Copyright information 

copyright: >
  Copyright &copy; 2022 - Present Docs –
  <a href="#__consent">Change cookie settings</a>

# Third-party plugins supported by Material Mkdocs

plugins:
  - search
  

# Markdown extensions supported by Material-Mkdocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
